name: radio_odan_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  audio_service: ^0.18.12
  just_audio_background: ^0.0.1-beta.7
  shimmer: ^3.0.0
  youtube_player_flutter: ^9.1.2
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  rxdart: ^0.28.0
  share_plus: ^11.0.0
  image_picker: ^1.1.2
  dio: ^5.5.0
  cookie_jar: ^4.0.6
  dio_cookie_manager: ^3.3.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.2
  flutter_animate: ^4.2.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_messaging: ^16.0.1
  google_sign_in: ^6.1.6
  app_links: ^6.1.1
  http: ^1.2.2

  flutter_localizations:
    sdk: flutter
  flutter_html: ^3.0.0
  flutter_dotenv: ^6.0.0
  logger: ^2.0.2+1
  collection: ^1.18.0
  provider: ^6.1.1
  google_fonts: ^6.1.0
  html: ^0.15.4
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  web_socket_channel: ^3.0.3
  pusher_channels_flutter: ^2.1.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

# Configure app launcher icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # Minimum Android SDK version required by your app
  web:
    generate: true
    image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # Adjust icon size for Windows if needed
  macos:
    generate: true
    image_path: "assets/logo.png"
  linux:
    generate: true
    image_path: "assets/logo.png"
